# Generated by Django 4.2.5 on 2023-09-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comentario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='date_added',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='text',
            new_name='texto',
        ),
    ]
